# Generated by Django 3.1.2 on 2020-11-09 22:58

from django.db import migrations, models
import posts.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('number_of_likes', models.PositiveIntegerField(default=0)),
                ('post_type', models.TextField(choices=[(0, 'Text'), (1, 'Image'), (2, 'Video')], default=posts.enums.PostTypes['TEXT'])),
                ('privacy_settings', models.TextField(choices=[(0, 'PRIVATE'), (1, 'PUBLIC')], default=posts.enums.AccessTypes['PRIVATE'])),
            ],
        ),
    ]
