# Generated by Django 3.1.3 on 2020-11-19 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='privacy_settings',
        ),
        migrations.AddField(
            model_name='post',
            name='content_url',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
