# Generated by Django 3.1.3 on 2020-11-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20201119_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='number_of_likes',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/imgs/posts/'),
        ),
    ]
