# Generated by Django 3.1.3 on 2020-11-19 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('mugshot', models.ImageField(blank=True, default='static/imgs/dummy_avatar.jpg', upload_to='static/imgs/')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=12, null=True)),
                ('privacy_settings', models.IntegerField(choices=[(0, 'PRIVATE'), (1, 'PUBLIC')], default=profiles.enums.AccessTypes['PUBLIC'])),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
