# Generated by Django 3.1.3 on 2020-12-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mugshot',
            field=models.ImageField(default='static/imgs/dummy_profile.jpg', upload_to='static/imgs/profile/'),
        ),
    ]
