# Generated by Django 3.1.3 on 2020-12-15 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20201215_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(default=['Leonard Nduwayo'], related_name='_profile_friends_+', to='profiles.Profile'),
        ),
    ]
